[2020-04-25 00:16:08] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-25 00:16:08] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-25 00:17:16] [CRITICAL] red.main: The main bot task didn't handle an exception and has crashed
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 502, in main
    loop.run_forever()
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 409, in shutdown_handler
    sys.exit(ExitCodes.SHUTDOWN)
SystemExit: ExitCodes.SHUTDOWN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 449, in red_exception_handler
    red_task.result()
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 362, in run_bot
    new_token = await interactive_config(
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/cli.py", line 72, in interactive_config
    await red._config.prefix.set([prefix])
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/config.py", line 257, in set
    await self.driver.set(self.identifier_data, value=value)
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/drivers/postgres/postgres.py", line 157, in set
    await self._execute(
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/drivers/postgres/postgres.py", line 255, in _execute
    return await method(query, *args)
  File "/home/pi/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 517, in execute
    async with self.acquire() as con:
  File "/home/pi/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 773, in __aenter__
    self.connection = await self.pool._acquire(self.timeout)
  File "/home/pi/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 609, in _acquire
    raise exceptions.InterfaceError('pool is closing')
asyncpg.exceptions._base.InterfaceError: pool is closing
[2020-04-25 00:17:16] [WARNING] red.main: Attempting to die as gracefully as possible...
[2020-04-25 00:17:16] [INFO] red.main: Shutting down from unhandled exception
[2020-04-25 00:17:16] [CRITICAL] red.main: Caught unhandled exception in task:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 502, in main
    loop.run_forever()
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 409, in shutdown_handler
    sys.exit(ExitCodes.SHUTDOWN)
SystemExit: ExitCodes.SHUTDOWN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 707, in cancel
    if child.cancel():
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 707, in cancel
    if child.cancel():
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 707, in cancel
    if child.cancel():
  [Previous line repeated 494 more times]
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 703, in cancel
    if self.done():
RecursionError: maximum recursion depth exceeded while calling a Python object
[2020-04-25 00:18:08] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-25 00:18:08] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-25 00:18:10] [CRITICAL] red.main: Caught unhandled exception in task: Task was destroyed but it is pending!
[2020-04-25 00:18:21] [INFO] red: Begin updating guild configs to support multiple mod/admin roles
[2020-04-25 00:18:21] [INFO] red: Done updating guild configs to support multiple mod/admin roles
[2020-04-25 00:18:21] [INFO] red: Moving shared API tokens to a custom group
[2020-04-25 00:22:01] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-25 00:22:01] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-25 00:22:01] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-25 00:29:06] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-25 00:29:06] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-25 00:29:07] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-25 00:51:40] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-25 00:51:40] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-25 00:51:40] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-25 00:57:42] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-25 00:57:42] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-25 00:57:43] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-25 01:15:34] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-25 01:15:34] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-25 01:15:35] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-26 13:18:27] [INFO] red.main: Signals.SIGHUP received. Quitting...
[2020-04-26 13:18:27] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-26 13:18:27] [INFO] red.main: Signals.SIGHUP received. Quitting...
[2020-04-26 13:18:27] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-26 13:18:27] [CRITICAL] red.main: Caught unhandled exception in task:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 502, in main
    loop.run_forever()
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 409, in shutdown_handler
    sys.exit(ExitCodes.SHUTDOWN)
SystemExit: ExitCodes.SHUTDOWN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 515, in main
    loop.run_until_complete(shutdown_handler(red, None, exc.code))
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 409, in shutdown_handler
    sys.exit(ExitCodes.SHUTDOWN)
SystemExit: ExitCodes.SHUTDOWN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/cogs/permissions/permissions.py", line 784, in _unload_all_rules
    all_rules = await self.config.custom(category).all()
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/config.py", line 304, in _get
    raw = await super()._get(default)
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/config.py", line 176, in _get
    ret = await self.driver.get(self.identifier_data)
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/drivers/postgres/postgres.py", line 141, in get
    result = await self._execute(
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/drivers/postgres/postgres.py", line 255, in _execute
    return await method(query, *args)
  File "/home/pi/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 553, in fetchval
    async with self.acquire() as con:
  File "/home/pi/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 773, in __aenter__
    self.connection = await self.pool._acquire(self.timeout)
  File "/home/pi/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 609, in _acquire
    raise exceptions.InterfaceError('pool is closing')
asyncpg.exceptions._base.InterfaceError: pool is closing
[2020-04-26 18:42:25] [INFO] red.main: Signals.SIGHUP received. Quitting...
[2020-04-26 18:42:25] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-26 18:42:25] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-26 18:43:31] [INFO] red.main: Signals.SIGHUP received. Quitting...
[2020-04-26 18:43:31] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-26 18:43:31] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-26 19:14:15] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-26 19:14:15] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-26 19:14:15] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-26 19:18:55] [INFO] red.main: Signals.SIGTERM received. Quitting...
[2020-04-26 19:18:55] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-26 19:18:55] [INFO] red.main: Signals.SIGHUP received. Quitting...
[2020-04-26 19:18:55] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-29 01:26:07] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:26:07] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-29 01:26:07] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-29 01:26:09] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:27:39] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:27:39] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-29 01:27:39] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-29 01:27:40] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:30:11] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:30:11] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-29 01:30:11] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-29 01:30:13] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:38:58] [INFO] red.main: Signals.SIGTERM received. Quitting...
[2020-04-29 01:38:58] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-29 01:38:58] [CRITICAL] red.main: Caught unhandled exception in task:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 502, in main
    loop.run_forever()
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/__main__.py", line 409, in shutdown_handler
    sys.exit(ExitCodes.SHUTDOWN)
SystemExit: ExitCodes.SHUTDOWN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/cogs/permissions/permissions.py", line 784, in _unload_all_rules
    all_rules = await self.config.custom(category).all()
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/config.py", line 304, in _get
    raw = await super()._get(default)
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/config.py", line 176, in _get
    ret = await self.driver.get(self.identifier_data)
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/drivers/postgres/postgres.py", line 141, in get
    result = await self._execute(
  File "/home/pi/.local/lib/python3.8/site-packages/redbot/core/drivers/postgres/postgres.py", line 255, in _execute
    return await method(query, *args)
  File "/home/pi/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 553, in fetchval
    async with self.acquire() as con:
  File "/home/pi/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 773, in __aenter__
    self.connection = await self.pool._acquire(self.timeout)
  File "/home/pi/.local/lib/python3.8/site-packages/asyncpg/pool.py", line 609, in _acquire
    raise exceptions.InterfaceError('pool is closing')
asyncpg.exceptions._base.InterfaceError: pool is closing
[2020-04-29 01:38:58] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-29 01:46:05] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:46:05] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-29 01:46:06] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-29 01:49:01] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:49:01] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-29 01:49:01] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-29 01:49:03] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:52:11] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:52:11] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-29 01:52:12] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-29 01:52:13] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:53:53] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 01:53:53] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-29 01:53:53] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-29 01:53:54] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 02:10:36] [WARNING] red.downloader: Invalid value of 'author' key (expected list, got str) in JSON information file at path: /home/pi/.local/share/Red-DiscordBot/data/CodeBot/cogs/RepoManager/repos/FlameCogs/info.json
[2020-04-29 03:44:39] [ERROR] red.downloader: ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lk971ypi/pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lk971ypi/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tw3es38g/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-ee49x9gz
         cwd: /tmp/pip-install-lk971ypi/pillow/
    Complete output (174 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.8
    creating build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/_util.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/_version.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/Image.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/features.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.8/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.8/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.ci'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/tmp/pip-install-lk971ypi/pillow/setup.py", line 860, in <module>
        setup(
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-lk971ypi/pillow/setup.py", line 694, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: jpeg
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lk971ypi/pillow/setup.py", line 914, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lk971ypi/pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lk971ypi/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tw3es38g/install-record.txt --single-version-externally-managed --compile --home=/tmp/pip-target-ee49x9gz Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[2020-04-29 03:44:39] [ERROR] red.downloader: Something went wrong when installing the following requirements: pillow
[2020-04-29 03:52:26] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-04-29 03:52:26] [INFO] red.main: Shutting down with exit code: ExitCodes.SHUTDOWN
[2020-04-29 03:52:26] [INFO] red.main: Please wait, cleaning up a bit more
[2020-04-29 03:52:29] [CRITICAL] red.main: Caught unhandled exception in task: Unclosed client session
